import type { NewParentForm, Parent } from "./types";

export const mockParents: Parent[] = [
  {
    id: "PAR-001",
    name: "Rajesh Sharma",
    email: "rajesh.sharma@email.com",
    phone: "+91 98765 43210",
    address: "Sector 15, Noida",
    linkedStudents: ["Aarav Sharma", "Diya Sharma"],
    qrAuthorized: true,
    emergencyContact: true,
    appAccess: true,
    lastActive: "2 hours ago",
    notificationPreferences: {
      boarding: true,
      drop: true,
      delays: true,
      alerts: true,
    },
  },
  {
    id: "PAR-002",
    name: "Amit Patel",
    email: "amit.patel@email.com",
    phone: "+91 98765 43211",
    address: "Indirapuram, Ghaziabad",
    linkedStudents: ["Diya Patel"],
    qrAuthorized: true,
    emergencyContact: true,
    appAccess: true,
    lastActive: "5 hours ago",
    notificationPreferences: {
      boarding: true,
      drop: true,
      delays: true,
      alerts: false,
    },
  },
  {
    id: "PAR-003",
    name: "Priya Gupta",
    email: "priya.gupta@email.com",
    phone: "+91 98765 43212",
    address: "Sector 18, Noida",
    linkedStudents: ["Rohan Gupta"],
    qrAuthorized: false,
    emergencyContact: true,
    appAccess: false,
    lastActive: "Never",
    notificationPreferences: {
      boarding: true,
      drop: true,
      delays: false,
      alerts: false,
    },
  },
  {
    id: "PAR-004",
    name: "Vikram Mehta",
    email: "vikram.mehta@email.com",
    phone: "+91 98765 43213",
    address: "Vasundhara, Ghaziabad",
    linkedStudents: ["Ananya Mehta"],
    qrAuthorized: true,
    emergencyContact: true,
    appAccess: true,
    lastActive: "1 day ago",
    notificationPreferences: {
      boarding: true,
      drop: true,
      delays: true,
      alerts: true,
    },
  },
];

export const createInitialParentForm = (): NewParentForm => ({
  name: "",
  email: "",
  phone: "",
  address: "",
  linkedStudents: "",
  qrAuthorized: true,
  emergencyContact: true,
  appAccess: true,
  notificationPreferences: {
    boarding: true,
    drop: true,
    delays: true,
    alerts: true,
  },
});
